### ISSUE TITLE
Pass allowed_mentions from the bot into Webhook.send

### ISSUE THREAD

**Issue by Koumes2** [DisnakeDev/disnake#721] opened 2022-08-29 17:07 UTC
### Summary

When using Webhook.send(), use the allowed_mentions set in the Bot

### What is the feature request for?

The core library

### The Problem

When using Webhook.send(), the webhook is using default AllowedMentions, which, [with the change that webhook's permissions are calculated using the respective bot's permissions](https://discord.com/developers/docs/change-log#changes-to-bot-permissions-for-interactions-and-webhooks), can cause issues.

### The Ideal Solution

Pass the allowed_mentions property from the bot

### The Current Solution

Use the allowed_mentions kwarg

**Comment by shiftinv** [comment] 2022-09-18 18:11
Webhooks that aren't manually created (i.e. those from `webhooks`, `fetch_webhook`, `create_webhook`, and things like `interaction.followup`) already use the client's `allowed_mentions`, so this shouldn't be an issue there.

The ones that don't inherit it are `Webhook.partial` and `Webhook.from_url`, since they are mostly detached from the client/bot system and are intended to also work outside of bots; those don't have any way of accessing the client's `allowed_mentions`.
If you want to use `allowed_mentions` with those, you'll need to pass it directly into `webhook.send()`, as you mentioned ^^

I'm closing this as working as intended, but feel free to comment if there's anything else.

**Closed by shiftinv** 2022-09-18 18:11 UTC
Labels: feature request
