### ISSUE TITLE
typing: `create_X_channel` enforces `CategoryChannel` types where `Snowflake` is fine

### ISSUE THREAD

**Issue by Skelmis** [DisnakeDev/disnake#1260] opened 2024-12-25 10:47 UTC
### Summary

`Guild.create_text_channel` and the like have incorrect types for category channels.

### Reproduction Steps

PoC code:
```py
        channel: disnake.TextChannel = await inter.guild.create_text_channel(
            channel_title,
            overwrites=overwrites,
            category=disnake.Object(id=bot.PARENT_CATEGORY_ID),
        )
```

Error:
`Expected type 'CategoryChannel | None', got 'Object' instead `

### Expected Results

`disnake.Object` to work fine given it's all that is required.

### Actual Results

See repro steps.

### Intents

N/A

### System Information

```markdown
poetry run python -m disnake -v
- Python v3.12.8-final
- disnake v2.9.3-final
    - disnake importlib.metadata: v2.9.3
- aiohttp v3.11.11
- system info: Linux 6.8.0-50-generic #51~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 21 12:03:03 UTC 2 x86_64
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by shiftinv** [comment] 2024-12-25 12:51
Thanks for the report! As far as I can tell, this is a duplicate of #1162, which will be fixed in the next release. `Object` is definitely supported here, the annotations unfortunately just didn't indicate that.

**Closed by shiftinv** 2024-12-25 12:51 UTC
Labels: unconfirmed bug
