### ISSUE TITLE
mutable default <class 'disnake.utils._MissingSentinel'> for field name is not allowed: use default_factory

### ISSUE THREAD

**Issue by donttellmeimcute** [DisnakeDev/disnake#831] opened 2022-10-28 17:37 UTC
### Summary

mutable default <class 'disnake.utils._MissingSentinel'> for field name is not allowed: use default_factory

### Reproduction Steps

from
from disnake.ext import commands
Exception has occurred: ValueError
mutable default <class 'disnake.utils._MissingSentinel'> for field name is not allowed: use default_factory
  File "test.py", line 4, in <module>
    from disnake.ext import commands 

### Minimal Reproducible Code

```python
#make a discord bot with python

import disnake
from disnake.ext import commands

client = commands.Bot(command_prefix="!", intents=disnake.Intents.all())
#make a slash command bot with python that send the message "hello world" when you type /hello

@client.slash_command(description="hello world")
async def hello(ctx):
    await ctx.send("hello world")

client.run("token")
```

### Expected Results

from disnake.ext import commands

client = commands.Bot(command_prefix="!", intents=disnake.Intents.all())

initialize the bot with that parameteres

### Actual Results

Exception has occurred: ValueError
mutable default <class 'disnake.utils._MissingSentinel'> for field name is not allowed: use default_factory
  File "test.py", line 4, in <module>
    from disnake.ext import commands 

### Intents

intents=disnake.Intents.all()

### System Information

```markdown
- Python v3.11.0-final
- disnake v2.6.1-final
- disnake pkg_resources: v2.6.1
- aiohttp v3.8.3
- system info: Windows 10 10.0.19044
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by onerandomusername** [comment] 2022-10-28 17:38
duplicate of #823

**Closed** 2022-10-28 17:39 UTC
Labels: unconfirmed bug
